- image: images/test.jpg
  link: https://example.com
  name: Test Machine
- name: Neu
  image: images/x.jpg
  image_details: []
  link: https://ex
  year: ''
  manufacturer: ''
  system: ''
  designer: ''
  software: ''
  artwork: ''
  sound: ''
  production: ''
  features: []
  notable_facts: []
