- name: "Williams: Funhouse"
  image: "https://tse4.mm.bing.net/th/id/OIP.4gLTC6VrQ5gNZdEs8jMniwHaFP?cb=iwc1&rs=1&pid=ImgDetMain"
  image_details:
    - "images/slides/8.jpg"
    - "images/slides/9.jpg"
    - "images/slides/10.jpg"
    - "images/slides/11.jpg"
    - "images/slides/12.jpg"
    - "images/slides/13.jpg"
    - "images/slides/14.jpg"
    - "images/slides/15.jpg"
  link: "https://www.ipdb.org/machine.cgi?id=966"
  year: "1990-12"
  manufacturer: "Williams"
  system: "Williams WPC (Fliptronics I)"
  designer: "Pat Lawlor"
  software: "Larry DeMar"
  artwork: "John Youssi"
  sound: "Chris Granner"
  production: "10.750 Stück"
  features:
    - "Sprechender Kopf „Rudy“, der auf das Spielgeschehen reagiert"
    - "Tag- und Nachtwechsel mit Einfluss auf das Gameplay"
    - "Zwei Flipperfinger, Multiball, Rampen, Zielgruppen"
  notable_facts:
    - "Gilt als Meilenstein im Flipperdesign"
    - "Rudy ist eines der ersten animierten, sprechenden Toys im Flipper"
