- name: "Christian Blatzheim"
  role: "Software"
  image: "images/team/blatzheimc.jpg"
  bio: "Auch er spielte als kleiner Junge an diesen komischen Kästen, Faszination pur. Diese Leidenschaft verblich zwar nach und nach durch das Aufkommen von anderen Daddelkisten namens C64, Amiga und letztlich PCs, war jedoch nie weg. Und als vor einigen Jahren private und immer größere Runden immer penetranter zum daddeln aufriefen, war die Flipperritis wieder voll ausgebrochen. „Und Zack, biste in ’nem Verein und dann auch noch Gründungsmitglied…“ Er hat auch unsere Spieltagstabelle verbrochen, die leider (oder zum Glück?) mittlerweile aus allen Nähten platzt („Waaaas? Mehr als 24 Spieler? Bisse bekloppt?“)."
- name: "Dirk Wallitzek"
  role: "Film / Foto & Grafik"
  image: "images/team/wallitzekd.jpg"
  bio: " "
