- image: "images/slides/Halle.jpg"
- image: "images/slides/5.jpg"
- image: "images/slides/6.jpg"
- image: "images/slides/7.jpg"
- image: "images/slides/8.jpg"
- image: "images/slides/9.jpg"
- image: "images/slides/10.jpg"
- image: "images/slides/11.jpg"
- image: "images/slides/12.jpg"
- image: "images/slides/13.jpg"
- image: "images/slides/14.jpg"
- image: "images/slides/15.jpg"
- image: "images/slides/16.jpg"
- image: "images/slides/17.jpg"
- image: "images/slides/18.jpg"
- image: "images/slides/19.jpg"
- image: "images/slides/20.jpg"
- image: "images/slides/21.jpg"
- image: "images/slides/22.jpg"
- image: "images/slides/23.jpg"
