- date: "2019-02"
  title: "Aixtraball erhält den ersten Flipper NIB"
  description: "Der Verein erhält den ersten Flipper 'new in Box'"
  image: "images/timeline/deadpoolnib.png"
- date: "2024-10"
  title: "45 Automaten erreicht"
  description: "Die Sammlung überschreitet die Marke von 45 spielbereiten Flippern."
#  image: "images/timeline/50automaten.jpg"
